workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build 
  - test

.job-defaults:
  image: $CONTAINER_IMAGE
  cache:
    key: node-$CI_COMMIT_REF_SLUG-$CONTAINER_IMAGE
    paths:
      - Node/.npm/ 
      - Node/node_modules/
    policy: pull
  before_script:
    - cd Node
    - set -a; source $STG_INTEGRATION_KEYS; set +a
  parallel:
    matrix:
      - CONTAINER_IMAGE: 
        - node:lts-alpine
        - node:14-alpine
        - node:16-alpine
        - node:18-alpine

build_Node:
  extends: .job-defaults
  stage: build
  cache:
    policy: pull-push
  script:
    - npm ci --cache .npm --prefer-offline

test_Node:
  extends: .job-defaults
  stage: test
  script:
    - npm test -- --verbose

lint_Node:
  extends: .job-defaults
  stage: test
  script:
    - npm run lint
  # only need to run the linting once
  parallel:
    matrix:
      - CONTAINER_IMAGE: 
        - node:lts-alpine